name: autoupdate
on:
  push:
    branches:
      - develop
      - 'releases/**'
jobs:
  autoupdate:
    name: autoupdate
    runs-on: ubuntu-18.04
    steps:
      - uses: docker://chinthakagodawita/autoupdate-action-unstable:v1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          PR_FILTER: "protected"
          PR_READY_STATE: "ready_for_review"